version: "3.8"

services:
  app:
    container_name: enba-mkpc
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    restart: unless-stopped
